name: codmgo2
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.2

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  http: ^1.0.0
  url_launcher: ^6.3.1
  shared_preferences: ^2.5.3
  logger: ^2.5.0
  geolocator: ^14.0.1
  permission_handler: ^12.0.0+1
  flutter_secure_storage: ^9.2.4
  provider: ^6.1.5
  flutter_native_splash: ^2.4.6
  flutter_displaymode: ^0.6.0
  flutter_local_notifications: ^19.2.1
  cupertino_icons: ^1.0.8
  animations: ^2.0.11
  intl: ^0.19.0
  image_picker: ^1.1.2
  device_info_plus: ^11.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter_native_splash:
  android: true
  ios: true
  web: true
  color: "#D64151"
  color_dark: "#121212"
  image: assets/codm_logo.png
  image_dark: assets/codm_logo.png
  android_gravity: center
  ios_content_mode: center
  web_image_mode: center
  android_screen_orientation: portrait
  fullscreen: true

flutter:
  uses-material-design: true

  assets:
    - assets/salesforce_logo.png
    - assets/codm_logo.png

  fonts:
    - family: HelveticaNeue
      fonts:
        - asset: assets/fonts/HelveticaNeueBlack.otf
          weight: 900
        - asset: assets/fonts/HelveticaNeueBold.otf
          weight: 700
        - asset: assets/fonts/HelveticaNeueHeavy.otf
          weight: 800
        - asset: assets/fonts/HelveticaNeueMedium.otf
          weight: 500
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font.